name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: |
          parking-system-web-UI/package-lock.json
          API-Service/package-lock.json
    
    - name: Install Angular dependencies
      run: |
        cd parking-system-web-UI
        npm ci
    
    - name: Build Angular app
      run: |
        cd parking-system-web-UI
        npm run build
    
    - name: Install API dependencies
      run: |
        cd API-Service
        npm ci
    
    - name: Create deployment package
      run: |
        mkdir deploy
        cp -r API-Service/* deploy/
        cp package.json deploy/
        ls -la deploy/
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_APP_NAME }}
        package: ./deploy